### ISSUE TITLE
Why no update?

### ISSUE THREAD

**Issue by fingermark** [trygve-lie/yocto.js#22]
Why no update?  Also, just curious, but why do the results of `get` get passed to a callback instead of just returned?  Is get non-blocking?

**Comment by trygve-lie** [comment]
I'm not quite sure what you mean with "Why no update". I'm working on a couple of issues and features so a new version will be pushed soon.

There is a couple of reasons why a callback is used instead of just returning the value and one of them is to be async. The other reason is to be able to compose functions. Ex; if you do a get().each() that will all run in one operation instead of two operations is one did a query and then looped over the returned result. Iow: it also has to do with speed.

**Comment by fingermark** [comment]
Cool.  Thanks for the reply.  I get why you use the callback now.

With regards to the update, I was wondering how you update a record.

**Comment by trygve-lie** [comment]
I see. In a touple space there is no update method. Updates is done by taking the object you want to manipulate out of the db with the take() method, manipulate it and then insert it again with the put() method.
